### ISSUE TITLE
`t` function returns `never` for dynamic keys using `moduleResolution: "node"`

### ISSUE THREAD

**Issue by jpreis** [i18next/i18next#2077]
## 🐛 Bug Report

In `23.7.7` calls to `t` using a dynamic key return `never` when using `moduleResolution: "node"`.
With `moduleResolution: "bundler"` the return type is `string`.

## To Reproduce

[Codesandbox](https://codesandbox.io/p/devbox/i18next-d22d9s?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clps4exay00063b6iokar4qrb%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clps4exay00023b6ixdcjry94%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clps4exay00043b6iqpykg64v%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clps4exay00053b6i9soqv4sg%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B54.42276676551688%252C45.57723323448312%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clps4exay00023b6ixdcjry94%2522%253A%257B%2522id%2522%253A%2522clps4exay00023b6ixdcjry94%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clps6kibt00023b6hlb1ydshl%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A17%252C%2522startColumn%2522%253A15%252C%2522endLineNumber%2522%253A17%252C%2522endColumn%2522%253A15%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Fmain.ts%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clps6kibt00023b6hlb1ydshl%2522%257D%252C%2522clps4exay00053b6i9soqv4sg%2522%253A%257B%2522id%2522%253A%2522clps4exay00053b6i9soqv4sg%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522id%2522%253A%2522clps4gy3q00bn3b6h0bw51b2v%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clps4gy3q00bn3b6h0bw51b2v%2522%257D%252C%2522clps4exay00043b6iqpykg64v%2522%253A%257B%2522id%2522%253A%2522clps4exay00043b6iqpykg64v%2522%252C%2522activeTabId%2522%253A%2522clpsl5zr500li3b6h0nkcmkr4%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clps4exay00033b6i5fu9capu%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clps4exe40002efeacbg10fat%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clps4gt1300913b6hygib6if3%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522id%2522%253A%2522clpsl5zr500li3b6h0nkcmkr4%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clpsl5ztm000pegeaff84fux8%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15.227864583333329%257D)

- change `moduleResolution` from `"node"` to `"bundler"` in `tsconfig.json`

## Expected behavior

Calls to `t` should return `string` regardless of the `moduleResolution` being used.
In version `23.7.6.` this was still the case, see [Codesandbox](https://codesandbox.io/p/devbox/i18next-23-7-6-h5c3pw?file=%2Fsrc%2Fmain.ts%3A19%2C4&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clps4exay00063b6iokar4qrb%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clps4exay00023b6ixdcjry94%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clps4exay00043b6iqpykg64v%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clps4exay00053b6i9soqv4sg%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B54.42276676551688%252C45.57723323448312%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clps4exay00023b6ixdcjry94%2522%253A%257B%2522id%2522%253A%2522clps4exay00023b6ixdcjry94%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clps6kibt00023b6hlb1ydshl%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A19%252C%2522startColumn%2522%253A4%252C%2522endLineNumber%2522%253A19%252C%2522endColumn%2522%253A4%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Fmain.ts%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clptkggw700023b6h00zeq9pa%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A16%252C%2522startColumn%2522%253A23%252C%2522endLineNumber%2522%253A16%252C%2522endColumn%2522%253A23%257D%255D%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clps6kibt00023b6hlb1ydshl%2522%257D%252C%2522clps4exay00053b6i9soqv4sg%2522%253A%257B%2522id%2522%253A%2522clps4exay00053b6i9soqv4sg%2522%252C%2522activeTabId%2522%253A%2522clptkg88s025k3b6hdm1e50z6%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522id%2522%253A%2522clps4gy3q00bn3b6h0bw51b2v%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522type%2522%253A%2522SANDBOX_INFO%2522%252C%2522id%2522%253A%2522clptkg88s025k3b6hdm1e50z6%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clps4exay00043b6iqpykg64v%2522%253A%257B%2522id%2522%253A%2522clps4exay00043b6iqpykg64v%2522%252C%2522activeTabId%2522%253A%2522clpsl5zr500li3b6h0nkcmkr4%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clps4exay00033b6i5fu9capu%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clps4exe40002efeacbg10fat%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clps4gt1300913b6hygib6if3%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522id%2522%253A%2522clpsl5zr500li3b6h0nkcmkr4%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clpsl5ztm000pegeaff84fux8%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15.227864583333329%257D)

## Notes

I noticed that in the `package.json` of `i18next` there's a `"types"` entry pointing to `"./index.v4.d.ts"`. Removing this entry (in the installed package in `node_modules`) also changes the return type from `never` to `string`.

## Your Environment

- *i18next version*: `23.7.7`
- *TypeScript version*: `5.0.2`

**Comment by siarheipashkevich** [comment]
Any news?

**Comment by adrai** [comment]
If you know how this can be improved, feel free to suggest a PR

**Comment by jpreis** [comment]
We "fixed" it by creating a patch for the `package.json`:
```
diff --git a/package.json b/package.json
index 1ff1a1e044f620fe6980213e8131613aefeddb44..b8b9c330cc3a1a1c22265bc343dffa69961f9355 100644
--- a/package.json
+++ b/package.json
@@ -4,7 +4,7 @@
   "description": "i18next internationalization framework",
   "main": "./dist/cjs/i18next.js",
   "module": "./dist/esm/i18next.js",
-  "types": "./index.v4.d.ts",
+  "types": "./index.d.ts",
   "typesVersions": {
     "<5.0": {
       "typescript/t.d.ts": [

```

We reference the `index.d.ts` instead of the `index.v4.d.ts` file for `typings` -- this works, but I can't say that I understand why. 🙈

**Comment by danr-za** [comment]
We upgraded from 23.7.6 to 23.7.11 and Typescript from 5.3.2 to 5.3.3, and started getting issues with concatenated keys, e.g. `t(`key.${type}`)` - patching the package.json as in @jpreis 's comment fixed the issue.

**Comment by adrai** [comment]
It would be very helpful if someone with deeper TypeScript knowledge could help us in finding a better solution that addresses this in a less hacky way and keeps the support for ESM, CJS, TS v4, TS v5, different moduleResolutions i.e. bundler, etc...
alternatively, we may need to drop TypeScript V4 completely
@pedrodurek can you help?

**Comment by jpreis** [comment]
This issue was fixed with `v23.7.16` 👍

**Comment by afternoon2** [comment]
Hey Folks, I've just updated `i18next` to `23.7.19` and Typescript to `5.3.3` I'm still getting this issue:

```ts
const decisionText = i18n.t(
  `genericIntent.${decision.decision === 'Approve' ? 'approved' : 'rejected'}`
);

// later in a string:
`decisionText.toLowerCase()` // Property 'toLowerCase' does not exist on type 'never'
```

**Comment by temoncher** [comment]
Also experiencing the same issue "i18next": "^23.11.4", "typescript": "^5.4.5"

**Comment by ShMcK** [comment]
Same issue. "i18next": "^23.11.5", "typescript": "5.2.2"

**Comment by stefan-girlich** [comment]
Confirmed using i18next 23.11.5 and typescript 5.5.3.
@jpreis  Should this issue be re-opened?

**Comment by jpreis** [comment]
@stefan-girlich interesting, for us this is not an issue currently, we're also using `23.11.5`.

**Comment by RohanWeli** [comment]
same for me also: Same issue. "i18next": "^23.11.5", "typescript": "5.2.2"

**Comment by adrai** [comment]
> Can this be re-opened, definitely still an issue.

@jacquesg  please provide a minimal reproducible example by using the last i18next version...
//cc @marcalexiei
