### ISSUE TITLE
Interpolation and nesting do not work together

### ISSUE THREAD

**Issue by leider** [i18next/i18next#478]
Just run this:

```javascript
import i18n from '../../src/i18next';

describe('I18Next', function () {
  i18n.init({
              lng: 'en',
              resources: {
                en: {
                  translation: {
                    'key1': 'hello world',
                    'key2': 'It is: $t(key1)',
                    'key3': 'It is: {{val}}'
                  }
                }
              }
            });

  it('works', function () {
    expect(i18n.t('key1')).to.equal('hello world');
    expect(i18n.t('key2')).to.equal('It is: hello world');
    expect(i18n.t('key3', {val: 'hello world'})).to.equal('It is: hello world');
    expect(i18n.t('key3', {val: '$t(key1)'})).to.equal('It is: hello world');
  });

});
```

the latter "expect" fails.

Did I get it wrong? - It worked in previous version. - I need it fixed soon, other wise I have to find a workaround.

**Comment by jamuhl** [comment]
should be possible by changing order -> moving nesting to be applied after interpolation:

https://github.com/i18next/i18next/blob/master/src/Translator.js#L152

will try asap and publish a new version.

**Comment by leider** [comment]
cool

**Comment by jamuhl** [comment]
should work with v2.0.5

**Comment by leider** [comment]
nope. not here in my context. ping me if interested in details

**Comment by jamuhl** [comment]
https://github.com/i18next/i18next/commit/2ef8258fda0001e018044b54bf6fae5a1fe9e394#diff-747476354d875e3cac53b04a40f8be53R39 hoped this fixes it...but seems my test is a little different.

sure just add some details and i will check it again...

**Comment by leider** [comment]
looking forward to check it

**Comment by jamuhl** [comment]
seems i broken the build somehow....try with v2.0.8

see sample on i18next.com http://i18next.com/translate/nesting/#withinterpolatednestingvalue -- should work now

**Comment by leider** [comment]
Still does not seem to work for me. I'll try to create a small sample project to reproduce my issue. Currently I have a work around.

**Comment by leider** [comment]
Repo done: https://github.com/leider/i18nextDemo

**Comment by jamuhl** [comment]
will have a look later....strange

**Comment by leider** [comment]
I've updated a small part. Got it wrong by mistake.
must be 

       p #{t('toplevel.key3', {val: '$t(toplevel.key2)'})}

instead of

       p #{t('toplevel.key3', '$t(toplevel.key2)')}

**Comment by jamuhl** [comment]
both solved in 2.0.10 (i hope)

**Comment by leider** [comment]
looks great! - Will examine closer later today :)

**Comment by leider** [comment]
Confirmed
